### ISSUE TITLE
Remove ClusterRole and ClusterRoleBinding from the chart

### ISSUE THREAD

**Issue by rasheedamir** [stakater-charts/application#109]
As these applications are namespace'd scope; we should remove the cluster level resources like ClusterRole and ClusterRoleBinding

This chart should only support creation of resources which are only namespace scoped

**Comment by rasheedamir** [comment]
fixed by https://github.com/stakater-charts/application/pull/118

**Comment by aslafy-z** [comment]
Too bad, I was looking for a chart that supports ClusterRole and CRB resources. That one was perfect apart for that part :disappointed:
